blank_issues_enabled: false
contact_links:
  - name: My Discord Server
    url: https://discord.gg/KZwDvzthmK
    about: You can ask general questions or request features here instead of opening issues for them.